### ISSUE TITLE
Update Suggestions

### ISSUE THREAD

**Issue by 5b21r** [IgnacioPinedo/checklist-app#1]
# Features
### Drag itens and sections up and down only while editing the checklist
I recommend the icon (https://fonts.google.com/icons?selected=Material+Symbols+Outlined:drag_indicator:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=drag) for this feature and to be placed at the left side to the section/item name.

# Feedbacks
### 2. Change color of the trash bin icon to red, the plus (+) icon to blue and the double check mark to green)
Pallet color suggestions below

# Color Pallet Suggestion
### For detail color, such as icons I would try Fire Engine Red [#C9101C (RGB 201, 16, 28)] and Lime Green [#13CC35 (RGB 19, 204, 53)]
Link of the color pallet here: https://coolors.co/3d3d3d-c9101c-13cc35-ffffff

# UI References
###
![Screenshot 2024-02-05 at 21 41 37](https://github.com/IgnacioPinedo/checklist-app/assets/78862027/f1d2b971-8cc1-4b6d-9b18-65b3507cb9d5)
![Screenshot 2024-02-05 at 21 37 54](https://github.com/IgnacioPinedo/checklist-app/assets/78862027/e1785c4b-16fd-4f67-b8df-a22bf522bbe7)

**Comment by IgnacioPinedo** [comment]
Hey @5b21r regarding this feedback 

> remove all the plus (+) sign buttons from every item and only include it next to a section (meaning to add a new section) and next to the last item (meaning to add one more item).

What do you think about making a little close to what the ToDos app does and have the an empty item at the bottom of each list of item which, when filled up, would become an actual item and another empty one would take it's place? Like the following:

<img width="2056" alt="Screenshot 2024-02-27 at 5 28 22 PM" src="https://github.com/IgnacioPinedo/checklist-app/assets/18120227/1fa4947f-cee5-4347-999e-c2a74093384a">

And something similar for sections as well:

<img width="2056" alt="Screenshot 2024-02-27 at 5 31 03 PM" src="https://github.com/IgnacioPinedo/checklist-app/assets/18120227/844e71d0-37b1-44fa-9a75-80d3d01a5f2d">

**Comment by IgnacioPinedo** [comment]
@5b21r also on:

> Change color of the trash bin icon to red, the plus (+) icon to blue and the double check mark to green)

I do see the red and green colors on the `Color Pallet Suggestion` section, but I'm not seeing the blue one.

**Comment by 5b21r** [comment]
> Hey @5b21r regarding this feedback
> 
> > remove all the plus (+) sign buttons from every item and only include it next to a section (meaning to add a new section) and next to the last item (meaning to add one more item).
> 
> What do you think about making a little close to what the ToDos app does and have the an empty item at the bottom of each list of item which, when filled up, would become an actual item and another empty one would take it's place? Like the following:
> 
> <img alt="Screenshot 2024-02-27 at 5 28 22 PM" width="2000" src="https://private-user-images.githubusercontent.com/18120227/308386585-1fa4947f-cee5-4347-999e-c2a74093384a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODU3MjgsIm5iZiI6MTcwOTA4NTQyOCwicGF0aCI6Ii8xODEyMDIyNy8zMDgzODY1ODUtMWZhNDk0N2YtY2VlNS00MzQ3LTk5OWUtYzJhNzQwOTMzODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAxNTcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMmMxMzRiYTQ0MDRmN2JjMmE5ZDI0MzZjNTIxNjkwM2IyYjA0MGUzNTEwYzNiNTdlYWY2ZTkzNDc2N2ZmZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yvELr_7DVh7_0qtWU2o9PcBkaJA8JInMfN5AZ97-4bc">
> And something similar for sections as well:
> 
> <img alt="Screenshot 2024-02-27 at 5 31 03 PM" width="2000" src="https://private-user-images.githubusercontent.com/18120227/308386870-844e71d0-37b1-44fa-9a75-80d3d01a5f2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODU3MjgsIm5iZiI6MTcwOTA4NTQyOCwicGF0aCI6Ii8xODEyMDIyNy8zMDgzODY4NzAtODQ0ZTcxZDAtMzdiMS00NGZhLTlhNzUtODBkM2QwMWE1ZjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAxNTcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZTEzNmFjM2RkMjdjNjkzMjdkNWU4MWJhMmM2YzMyOTZkM2Q3NTYxYjZhMmE3NTYyZWM4YTA4MTU5MmJkYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hQNtVxp4Q1hqh2ibV2pXP-iV1FAkiallBPy7V7dzniI">

That is a perfect idea! let's try that!

**Comment by 5b21r** [comment]
> @5b21r also on:
> 
> > Change color of the trash bin icon to red, the plus (+) icon to blue and the double check mark to green)
> 
> I do see the red and green colors on the `Color Pallet Suggestion` section, but I'm not seeing the blue one.

You can use [[this pallete](https://coolors.co/3d3d3d-c9101c-13cc35-5b49e1-ffffff)]
