### ISSUE TITLE
Checklist Order Position

### ISSUE THREAD

**Issue by 5b21r** [IgnacioPinedo/checklist-app#8]
A filter kind of button could help to organize the checklists in specifics orders, such as:

- Alphabetical order (a-z and z-a)
- Date created (newest and oldest)
- Date modified (newest and oldest)
- Custom order (This one could enable a drag and drop function, similar to what we have while creating a checklist and re ordering the items)

**Comment by IgnacioPinedo** [comment]
I think we can probably do Alphabetical (A-Z and Z-A), Date Created, and Date Modified.

Custom order would be harder and would be set by user or admin users would have the ability to change, but it would only be useful for them.

I was thinking the UI could look something like this:
![image](https://github.com/user-attachments/assets/ebe85290-9d4d-4508-8f59-31f19c0dbaae)
