### ISSUE TITLE
Collapse and Expand Function

### ISSUE THREAD

**Issue by 5b21r** [IgnacioPinedo/checklist-app#9]
- Add a Collapse and Expand for each section of the checklist
- Add a Collapse and Expand all to close or open the entire checklist (meaning open or close all sections in one click of a button)

extra Suggestion: Make the checklist open with all collapsed by default

**Comment by IgnacioPinedo** [comment]
We already have the Expand/Collapse section:
![Screenshot 2024-11-27 at 2 03 45 PM](https://github.com/user-attachments/assets/b451647d-69ab-4f84-8f61-d091036991d6)

I think that what we can do if move the button to the left side of the title and add an extra one on top of all section, something like this:
![image](https://github.com/user-attachments/assets/e4bfaf82-abc4-4f79-82b8-959618be1261)

**Comment by 5b21r** [comment]
I apologize for my previous comment. You are right, the section collapse button already works.

And I agree with your suggestion. Moving the buttons to the left and adding a new one on top of everything to make the "Collapse/Expand all" seems to work just fine.
